name: Build

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone Tree
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison clang lld llvm python3 pip
          pip install protobuf grpcio-tools
      - name: Build
        run: |
          eval $(./3rdparty/nxdk/bin/activate -s)
          make -j$(nproc)
          mv bin/default.xbe bin/attach.xbe
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: |
            bin
          if-no-files-found: error
